module.exports = {
  // Parameter for the source files
  SOURCE_PARAMETER: [
    "AZIMUTH",
    "BITWISE",
    "BPOS",
    "DBTM",
    "DIFF",
    "DLS",
    "DMEA",
    "GASA",
    "GR",
    "GTF",
    "HKL",
    "INCLINATION",
    "MDOA",
    "MFI",
    "MFOP",
    "MSE",
    "MTF",
    "MWIT",
    "ONBTM",
    "ROP",
    "RPM",
    "SPM",
    "SPP",
    "TFLO",
    "TIMESTAMP",
    "TQA",
    "TVA",
    "TVD",
    "WOB",
  ],

  // SOURCE_DATA: {
  //   "0105": "Date",
  //   "0106": "Time",
  //   1984: "Well124",
  //   "0120": "RPM",
  //   "0123": "SPM1",
  //   "0124": "SPM2",
  //   "0121": "SPP",
  //   "0112": "BPOS",
  //   "0108": "DBTM",
  //   "0110": "DMEA",
  //   "0114": "HKLD",
  //   "0115": "HKLX",
  //   "0116": "WOB",
  //   "0117": "WOBX",
  //   "0113": "ROP",
  //   "0118": "TOR",
  //   "0119": "TQX",
  // },

  DEPTH_DATA: {
    Well124: "Erdos Miller",
  },

  // Mnemonic names for the source files
  STD_MNEMONIC: {
    AZIMUTH: "AZIMUTH",
    BITWISE: "BITWISE",
    BPOS: "BPOS",
    DBTM: "DBTM",
    DIFF: "DIFF",
    DLS: "DLS",
    DMEA: "DMEA",
    GASA: "GASA",
    GR: "GR",
    GTF: "GTF",
    HKL: "HKL",
    INCLINATION: "INCLINATION",
    MDOA: "MDOA",
    MFI: "MFI",
    MFOP: "MFOP",
    MSE: "MSE",
    MTF: "MTF",
    MWIT: "MWIT",
    ONBTM: "ONBTM",
    ROP: "ROP",
    RPM: "RPM",
    SPM: "SPM",
    SPP: "SPP",
    TFLO: "TFLO",
    TIMESTAMP: "TIMESTAMP",
    TQA: "TQA",
    TVA: "TVA",
    TVD: "TVD",
    WOB: "WOB",
  },

  // Mnemonic names for the source files
  STD_MNEMONIC_DISPLAYNAME: {
    AZIMUTH: "MWD AZIMUTH (CORRECTED)",
    BITWISE: "BITWISE",
    BPOS: "BLOCK POSITION",
    DBTM: "BIT DEPTH",
    DIFF: "DIFF PRESS",
    DLS: "DLS",
    DMEA: "HOLE DEPTH",
    GASA: "GASA",
    GR: "MG1",
    GTF: "SGTF_157",
    HKL: "HOOK LOAD",
    INCLINATION: "INCLINATION",
    MDOA: "MDOA",
    MFI: "GPM",
    MFOP: "MFOP",
    MSE: "MSE",
    MTF: "SMTF_157",
    MWIT: "MWIT",
    ONBTM: "BOTTOM",
    ROP: "ROP",
    RPM: "RPM",
    SPM: "SPM1",
    SPP: "SPP",
    TFLO: "TFLO",
    TIMESTAMP: "TIME",
    TQA: "TORQUE",
    TVA: "TVA",
    TVD: "TVD",
    WOB: "WOB",
  },

  // Unit for the source file
  UNIT: {
    AZIMUTH: "degree",
    BITWISE: "in",
    BPOS: "m",
    DBTM: "m",
    DIFF: "psi",
    DLS: "dega",
    DMEA: "m",
    GASA: "%",
    GR: "API",
    GTF: "degree",
    HKL: "klb",
    INCLINATION: "degree",
    MDOA: null,
    MFI: "galUS/min",
    MFOP: "%",
    MSE: "psi",
    MTF: "degree",
    MWIT: "g/cc",
    ONBTM: null,
    ROP: "m/hr",
    RPM: "rpm",
    SPM: "spm",
    SPP: "psi",
    TFLO: "l/min",
    TIMESTAMP: "s",
    TQA: "klb.ft",
    TVA: "bbl",
    TVD: "m",
    WOB: "klb",
  },

  // UNIT: {
  //   "0105": "yymmdd",
  //   "0106": "hhmmss",
  //   "0120": "rpm",
  //   "0123": "SPM",
  //   "0124": "SPM",
  //   "0121": "psi",
  //   "0112": "ft",
  //   "0108": "ft",
  //   "0110": "ft",
  //   "0114": "klb",
  //   "0115": "klb",
  //   "0116": "klb",
  //   "0117": "klb",
  //   "0113": "ft/h",
  //   "0118": "klbf",
  //   "0119": "klbf",
  // },

  DESCRIPTION: {
    AZIMUTH: "MWD AZIMUTH (CORRECTED)",
    BITWISE: "Bit Size",
    BPOS: "Block Position",
    DBTM: "Bit Depth (measured)",
    DIFF: "Differential Pressure",
    DLS: "Survey Dogleg Severity",
    DMEA: "Hole Depth (measured)",
    GASA: "Gas",
    GR: "GAMMA RAY READING (UNCORRECTED)",
    GTF: "MWD GRAVITY TOOL FACE",
    HKL: "Hook Load",
    INCLINATION: "Survey - Inclination",
    MDOA: "Mud Density Out Average",
    MFI: "MUD FLOW IN",
    MFOP: "FLOW OUT OF HOLE MEASURED AS A PERCENTAGE",
    MSE: "Mechanical Specific Energy",
    MTF: "MWD MAGNETIC TOOL FACE",
    MWIT: "Mud Weight",
    ONBTM: "BIT ON/OFF BOTTOM",
    ROP: "Rate of Penetration",
    RPM: "Rotation per Minute",
    SPM: "PUMP STROKE RATE (STROKES/MINUTE)",
    SPP: "Stand Pipe Pressure",
    TFLO: "Flow Rate",
    TIMESTAMP: "Time of measurement",
    TQA: "Rotary Torque",
    TVA: "TANK VOLUME (ACTIVE)",
    TVD: "True Vertical Depth",
    WOB: "Weight on Bit",
  },

  SOURCE_LOG_DATA: {
    customer: "Test123",
    // log: "time",
    well: "13220",
    wellbore: "13220",
    // sourceid: "789da98a89987adsa979ads",
    // "end_depth" : 11818.0,
    // "end_time" : ISODate("2020-09-21T07:00:11.000Z"),
    // laststatusupdate: "2021-11-24T05:57:50.537Z",
    // log_data: "source_time_data",
    secondsdataavailability: false,
    // "start_depth" : 1.0,
    // "start_time" : ISODate("2020-09-03T08:56:32.000Z"),
    // count:'',
    status: "UPDATING",
    well_name: "CHALK TALK B #3H",
    mode: "Node",
  },
};
